In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.6'

In [4]:
np.arange(1 ,5, 0.5) # start , end(excluding), step_size

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
np.zeros((2,3)), np.ones((3,3))

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [6]:
np.empty((4,3)) # fills with garbage values

array([[1.25640986e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 2.58206076e-057],
       [4.90939174e-062, 4.50335687e+174, 7.86788744e-067],
       [6.23369670e+174, 1.51341063e+160, 1.65854630e-076]])

In [9]:
np.linspace(1,5, 10) # linearly seperated numbers , between start(first argument), stop(second argument) and number of elements(num of elements to be shown)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Array properties
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:\n", arr)
print("\nNumber of dimensions (ndim):", arr.ndim)
print("Shape (rows, columns):", arr.shape)
print("Total size (number of elements):", arr.size)
print("Data type:", arr.dtype)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Number of dimensions (ndim): 2
Shape (rows, columns): (3, 4)
Total size (number of elements): 12
Data type: int64


In [16]:
print("Item size (bytes per element):", arr.itemsize)
# Outputs the size (in bytes) of one element in the array.
# int32 → 4 bytes
# float64 → 8 bytes
# uint8 → 1 byte


Item size (bytes per element): 8


In [18]:
print("Total bytes:", arr.nbytes)
# Outputs the total number of bytes used by the entire array.
# element size x number of elements

Total bytes: 96


In [38]:
arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
arr.flatten() # returned a flattened version of the given matrix, this flattened version will be present as a new array.


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
ref = arr.ravel() # ravel returns a view of the original array , provided the returned array is changed, then the original array will also change
print(ref)
ref[3] = 44
ref , arr

[1 2 3 4 5 6 7 8 9]


(array([ 1,  2,  3, 44,  5,  6,  7,  8,  9]),
 array([[ 1,  2,  3],
        [44,  5,  6],
        [ 7,  8,  9]]))

In [40]:
flatten_c = arr.flatten(order='C')  # Row-major (C-style)
flatten_f = arr.flatten(order='F')  # Column-major (Fortran-style)
print("\nC-order (row-major):", flatten_c)
print("F-order (column-major):", flatten_f)


C-order (row-major): [ 1  2  3 44  5  6  7  8  9]
F-order (column-major): [ 1 44  7  2  5  8  3  6  9]


In [41]:
# Boolean masking
arr = np.array([1, 5, 3, 8, 2, 9, 4, 6, 7])
print("Original array:", arr)

# Create boolean mask
mask = arr > 5
print("\nMask (arr > 5):", mask)
print("Elements greater than 5:", arr[mask])

# Multiple conditions
mask_multiple = (arr > 3) & (arr < 8)
print("\nElements between 3 and 8:", arr[mask_multiple])

# Boolean indexing on 2D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", arr_2d)
print("Elements > 5:", arr_2d[arr_2d > 5])

Original array: [1 5 3 8 2 9 4 6 7]

Mask (arr > 5): [False False False  True False  True False  True  True]
Elements greater than 5: [8 9 6 7]

Elements between 3 and 8: [5 4 6 7]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elements > 5: [6 7 8 9]


In [42]:
# Fancy indexing with integer arrays
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("Original array:", arr)

# Select specific indices
indices = [1, 3, 5, 7]
print("Elements at indices [1, 3, 5, 7]:", arr[indices])

# 2D fancy indexing
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print("\n2D Array:\n", arr_2d)

# Select specific rows
row_indices = [0, 2, 3]
print("\nRows [0, 2, 3]:\n", arr_2d[row_indices])

# Select specific elements
row_idx = [0, 1, 2, 3]
col_idx = [0, 1, 2, 3]
print("\nDiagonal elements:", arr_2d[row_idx, col_idx])

Original array: [10 20 30 40 50 60 70 80 90]
Elements at indices [1, 3, 5, 7]: [20 40 60 80]

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rows [0, 2, 3]:
 [[ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal elements: [ 1  6 11 16]


In [43]:
# Broadcasting - operations between arrays of different shapes
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_1d = np.array([10, 20, 30])

print("2D Array:\n", arr_2d)
print("\n1D Array:", arr_1d)

# Broadcasting: 1D array is added to each row of 2D array
result = arr_2d + arr_1d
print("\n2D + 1D (broadcasting):\n", result)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array: [10 20 30]

2D + 1D (broadcasting):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [45]:
# More broadcasting examples
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
col_vector = np.array([[10], [20]])

print("\n2D + Column vector:\n", arr_2d + col_vector)

# Broadcasting with different dimensions
arr_3d = np.ones((2, 3, 4))
arr_1d = np.array([1, 2, 3, 4])
print("\n3D shape:", arr_3d.shape)
print("1D shape:", arr_1d.shape)
result = arr_3d + arr_1d
print("Result shape:", result.shape)
print(result)


2D + Column vector:
 [[11 12 13]
 [24 25 26]]

3D shape: (2, 3, 4)
1D shape: (4,)
Result shape: (2, 3, 4)
[[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]]


In [49]:
arr = np.array([1,2,3,4,5,6])
print(arr.var()) # outputs variance : sigma((x - u)**2) / N
u = np.mean(arr)
var =  np.sum((arr - u)**2) / len(arr)
print(var)

2.9166666666666665
2.9166666666666665


In [50]:
# Min, max, argmin, argmax
arr = np.array([23, 45, 12, 67, 34, 89, 56, 11])

print("Array:", arr)
print("\nMinimum value:", np.min(arr))
print("Maximum value:", np.max(arr))
print("Index of minimum (argmin):", np.argmin(arr))
print("Index of maximum (argmax):", np.argmax(arr))

# 2D array
arr_2d = np.array([[23, 45, 12],
                   [67, 34, 89],
                   [56, 11, 78]])

print("\n2D Array:\n", arr_2d)
print("Overall min:", np.min(arr_2d))
print("Overall max:", np.max(arr_2d))
print("Index of overall min (flattened):", np.argmin(arr_2d))
print("Index of overall max (flattened):", np.argmax(arr_2d))

Array: [23 45 12 67 34 89 56 11]

Minimum value: 11
Maximum value: 89
Index of minimum (argmin): 7
Index of maximum (argmax): 5

2D Array:
 [[23 45 12]
 [67 34 89]
 [56 11 78]]
Overall min: 11
Overall max: 89
Index of overall min (flattened): 7
Index of overall max (flattened): 5


In [51]:
# Axis-based operations
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("2D Array:\n", arr_2d)

# Axis 0: operations along columns (down the rows)
print("\nSum along axis 0 (column-wise):", np.sum(arr_2d, axis=0))
print("Mean along axis 0:", np.mean(arr_2d, axis=0))
print("Max along axis 0:", np.max(arr_2d, axis=0))

# Axis 1: operations along rows (across the columns)
print("\nSum along axis 1 (row-wise):", np.sum(arr_2d, axis=1))
print("Mean along axis 1:", np.mean(arr_2d, axis=1))
print("Max along axis 1:", np.max(arr_2d, axis=1))

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sum along axis 0 (column-wise): [15 18 21 24]
Mean along axis 0: [5. 6. 7. 8.]
Max along axis 0: [ 9 10 11 12]

Sum along axis 1 (row-wise): [10 26 42]
Mean along axis 1: [ 2.5  6.5 10.5]
Max along axis 1: [ 4  8 12]


In [52]:
print("Logarithm (natural):", np.log(arr))
print("Log10:", np.log10(arr))
print("Log2:", np.log2(arr))

Logarithm (natural): [3.13549422 3.80666249 2.48490665 4.20469262 3.52636052 4.48863637
 4.02535169 2.39789527]
Log10: [1.36172784 1.65321251 1.07918125 1.8260748  1.53147892 1.94939001
 1.74818803 1.04139269]
Log2: [4.52356196 5.4918531  3.5849625  6.06608919 5.08746284 6.47573343
 5.80735492 3.45943162]


In [53]:
# Trigonometric functions
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("Angles (radians):", angles)
print("\nSine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles[:4]))  # Exclude pi/2 to avoid infinity

# Rounding functions
arr = np.array([1.2, 2.5, 3.7, 4.1, -1.8, -2.3])
print("\nOriginal:", arr)
print("Round:", np.round(arr))
print("Floor:", np.floor(arr))
print("Ceiling:", np.ceil(arr))
print("Absolute:", np.abs(arr))

Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]

Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.         0.57735027 1.         1.73205081]

Original: [ 1.2  2.5  3.7  4.1 -1.8 -2.3]
Round: [ 1.  2.  4.  4. -2. -2.]
Floor: [ 1.  2.  3.  4. -2. -3.]
Ceiling: [ 2.  3.  4.  5. -1. -2.]
Absolute: [1.2 2.5 3.7 4.1 1.8 2.3]


In [54]:
# np.where for conditional operations
arr = np.array([1, 5, 3, 8, 2, 9, 4, 6, 7])

print("Original array:", arr)

# Replace values greater than 5 with 100, otherwise keep original
result = np.where(arr > 5, 100, arr)
print("\nReplace > 5 with 100:", result)

# Replace values greater than 5 with 'High', otherwise 'Low'
result = np.where(arr > 5, 'High', 'Low')
print("High/Low classification:", result)

Original array: [1 5 3 8 2 9 4 6 7]

Replace > 5 with 100: [  1   5   3 100   2 100   4 100 100]
High/Low classification: ['Low' 'Low' 'Low' 'High' 'Low' 'High' 'Low' 'High' 'High']


In [55]:
# np.where with multiple conditions
arr = np.array([1, 5, 3, 8, 2, 9, 4, 6, 7])

print("Original array:", arr)

# Nested conditions: > 7 -> 'High', 4-7 -> 'Medium', < 4 -> 'Low'
result = np.where(arr > 7, 'High', np.where(arr >= 4, 'Medium', 'Low'))
print("\nThree-level classification:", result)

# Get indices where condition is True
indices = np.where(arr > 5)
print("\nIndices where arr > 5:", indices[0])
print("Values at those indices:", arr[indices])

Original array: [1 5 3 8 2 9 4 6 7]

Three-level classification: ['Low' 'Medium' 'Low' 'High' 'Low' 'High' 'Medium' 'Medium' 'Medium']

Indices where arr > 5: [3 5 7 8]
Values at those indices: [8 9 6 7]


In [56]:
# Matrix multiplication
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("Matrix A (2x3):\n", A)
print("\nMatrix B (3x2):\n", B)

# Matrix multiplication
C = np.dot(A, B)
print("\nA · B (2x2):\n", C)

# Using @ operator
C_alt = A @ B
print("\nUsing @ operator:\n", C_alt)

# Using np.matmul
C_matmul = np.matmul(A, B)
print("\nUsing np.matmul:\n", C_matmul)

Matrix A (2x3):
 [[1 2 3]
 [4 5 6]]

Matrix B (3x2):
 [[ 7  8]
 [ 9 10]
 [11 12]]

A · B (2x2):
 [[ 58  64]
 [139 154]]

Using @ operator:
 [[ 58  64]
 [139 154]]

Using np.matmul:
 [[ 58  64]
 [139 154]]


In [57]:
# Transpose of a matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Original matrix A (2x3):\n", A)
print("Shape:", A.shape)

# Transpose using .T
A_transpose = A.T
print("\nTranspose A^T (3x2):\n", A_transpose)
print("Shape:", A_transpose.shape)

# Transpose using np.transpose()
A_transpose_func = np.transpose(A)
print("\nUsing np.transpose():\n", A_transpose_func)

Original matrix A (2x3):
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transpose A^T (3x2):
 [[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)

Using np.transpose():
 [[1 4]
 [2 5]
 [3 6]]


In [61]:
# Matrix inverse
A = np.array([[4, 7,2],
              [2, 6,1],
              [4,5,6]])

print("Matrix A:\n", A)

# Inverse
A_inv = np.linalg.inv(A)
print("\nInverse A^-1:\n", A_inv)

# Verify: A · A^-1 = I (Identity matrix)
identity = A @ A_inv
print("\nA · A^-1 (should be identity):\n", np.round(identity, 10))


Matrix A:
 [[4 7 2]
 [2 6 1]
 [4 5 6]]

Inverse A^-1:
 [[ 0.775 -0.8   -0.125]
 [-0.2    0.4    0.   ]
 [-0.35   0.2    0.25 ]]

A · A^-1 (should be identity):
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [62]:
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

print("\nMatrix B:\n", B)
print("Determinant of B:", np.linalg.det(B))


Matrix B:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinant of B: 0.9999999999999964


In [63]:
# Eigenvalues and eigenvectors
A = np.array([[4, 2],
              [1, 3]])

print("Matrix A:\n", A)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Verify: A · v = λ · v (for first eigenvector)
v1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]

Av1 = A @ v1
lambda_v1 = lambda1 * v1

print("\nVerification for first eigenvalue/eigenvector:")
print("A · v1 =", Av1)
print("λ1 · v1 =", lambda_v1)
print("Are they equal?", np.allclose(Av1, lambda_v1))

Matrix A:
 [[4 2]
 [1 3]]

Eigenvalues: [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Verification for first eigenvalue/eigenvector:
A · v1 = [4.47213595 2.23606798]
λ1 · v1 = [4.47213595 2.23606798]
Are they equal? True


In [64]:
# Singular Value Decomposition (SVD)
# A = U · Σ · V^T

A = np.array([[3, 1, 1],
              [-1, 3, 1]])

print("Matrix A (2x3):\n", A)

# Perform SVD
U, s, VT = np.linalg.svd(A)

print("\nU matrix (left singular vectors):\n", U)
print("Shape:", U.shape)

print("\nSingular values (s):", s)

print("\nV^T matrix (right singular vectors transposed):\n", VT)
print("Shape:", VT.shape)

Matrix A (2x3):
 [[ 3  1  1]
 [-1  3  1]]

U matrix (left singular vectors):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Shape: (2, 2)

Singular values (s): [3.46410162 3.16227766]

V^T matrix (right singular vectors transposed):
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]
Shape: (3, 3)


In [65]:
# Reconstruct the original matrix from SVD components
# Create Sigma matrix from singular values
Sigma = np.zeros((U.shape[1], VT.shape[0]))
Sigma[:len(s), :len(s)] = np.diag(s)

print("Sigma matrix:\n", Sigma)

# Reconstruct A
A_reconstructed = U @ Sigma @ VT
print("\nReconstructed A:\n", A_reconstructed)

print("\nOriginal A:\n", A)
print("\nAre they equal?", np.allclose(A, A_reconstructed))

Sigma matrix:
 [[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]

Reconstructed A:
 [[ 3.  1.  1.]
 [-1.  3.  1.]]

Original A:
 [[ 3  1  1]
 [-1  3  1]]

Are they equal? True


In [72]:
np.random.seed(42)
# Random number generation
# Random floats between 0 and 1
random_floats = np.random.rand(5)
print("Random floats [0, 1):", random_floats)

# Random floats from standard normal distribution
random_normal = np.random.randn(5)
print("\nRandom from standard normal:", random_normal)

# Random integers
random_ints = np.random.randint(1, 100, size=10)
print("\nRandom integers [1, 100):", random_ints)

# Random floats in a range
random_range = np.random.uniform(10, 20, size=5)
print("\nRandom floats [10, 20):", random_range)

Random floats [0, 1): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Random from standard normal: [ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017]

Random integers [1, 100): [22 89 49 91 59 42 92 60 80 15]

Random floats [10, 20): [14.56069984 17.85175961 11.99673782 15.14234438 15.92414569]


In [69]:
# Random 2D arrays
random_2d = np.random.rand(3, 4)
print("Random 2D array (3x4):\n", random_2d)

# Random with specific distributions
random_normal_dist = np.random.normal(loc=50, scale=10, size=5)
print("\nNormal distribution (mean=50, std=10):", random_normal_dist)

random_binomial = np.random.binomial(n=10, p=0.5, size=5)
print("\nBinomial distribution (n=10, p=0.5):", random_binomial)

random_poisson = np.random.poisson(lam=5, size=5)
print("\nPoisson distribution (lambda=5):", random_poisson)

Random 2D array (3x4):
 [[0.31280195 0.32623514 0.03536491 0.16812982]
 [0.898124   0.52548713 0.64785566 0.98321649]
 [0.4604864  0.89167299 0.34103157 0.24263899]]

Normal distribution (mean=50, std=10): [51.21266189 37.02153604 64.65338039 41.13146605 48.10102468]

Binomial distribution (n=10, p=0.5): [6 7 4 3 5]

Poisson distribution (lambda=5): [4 6 2 6 9]


In [70]:
# Random sampling from an array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:", arr)

# Random choice (with replacement)
sample_with_replacement = np.random.choice(arr, size=5, replace=True)
print("\nSample with replacement (size=5):", sample_with_replacement)

# Random choice (without replacement)
sample_without_replacement = np.random.choice(arr, size=5, replace=False)
print("Sample without replacement (size=5):", sample_without_replacement)

# Random choice with probabilities
probabilities = [0.1, 0.05, 0.05, 0.1, 0.2, 0.2, 0.1, 0.05, 0.05, 0.1]
weighted_sample = np.random.choice(arr, size=10, p=probabilities, replace=True)
print("\nWeighted sample:", weighted_sample)

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Sample with replacement (size=5): [50 50 70 80 10]
Sample without replacement (size=5): [50 30 10 60 20]

Weighted sample: [10 60 40 80 20 50 90 60 70 40]


In [71]:
# Shuffling arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Shuffle in-place (modifies the original array)
arr_copy = arr.copy()
np.random.shuffle(arr_copy)
print("Shuffled array:", arr_copy)

# Permutation (returns a shuffled copy)
arr_permuted = np.random.permutation(arr)
print("Permutation:", arr_permuted)
print("Original unchanged:", arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Shuffled array: [ 6  5  8  7  3  4  9 10  1  2]
Permutation: [ 7  4  1  8  5  2  6 10  3  9]
Original unchanged: [ 1  2  3  4  5  6  7  8  9 10]
